services:
  - type: web
    name: fullstack-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    staticPublishPath: build
    autoDeploy: true
